// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250723144642_TestData")]
    partial class TestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Iphone 15 Description",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "Iphone 15",
                            Price = 70000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Iphone 14 Description",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Name = "Iphone 14",
                            Price = 50000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Iphone 13 Description",
                            ImageUrl = "3.jpg",
                            IsActive = false,
                            Name = "Iphone 13",
                            Price = 35000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "Iphone 12 Description",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Name = "Iphone 12",
                            Price = 20000m,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
